functional:
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность создавать новую игру
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
implicit:
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Главная страница сайта должна загружаться не более чем за 3 секунды